### PR TITLE
Make everything PEP8 compliant

### PR DESCRIPTION
**Pull request by jonasfs**
I noticed some inconsistency regarding the amount of spaces, order of imports, line length and so on, so I ran everything through [autopep8](https://pypi.org/project/autopep8/) to get consistent formatting.

This is just a suggestion though, feel free to request changes (I understand not everyone agrees with PEP8 and thats ok) or to close the PR if you feel the changes are not interesting right now.

Ideally this should be merged after #19  (assuming that one is accepted).

### CODE REVIEW

**Review by rizqirizqi — APPROVED** [review]
Nice, we need this, it will be better if it runs automatically on save/commit. I will merge this for now.

**Comment by jonasfs** [comment]
Cool! I noticed that there are new merge conflicts on some of the PRs I submited, I'll get then resolved in a couple of minutes!

**Comment by rizqirizqi** [comment]
I just resolved and merged https://github.com/rizqirizqi/scientific-name-fetcher/pull/19 :joy: 
You can continue to resolve the other PRs, thanks!

**Comment by jonasfs** [comment]
This one is ready!

**Review by rizqirizqi — APPROVED** [review]

**Pull request merged**
